### ISSUE TITLE
Setup tags on Docker Hub

### ISSUE THREAD

**Issue by smazurov** [MeteoGroup/concourse-ci#2]
Currently, there is 2 tags on docker hub, `latest` and `test`. It would be great if tags were set up for each version. You can do so by tagging commits in `github` and having automatic build on docker hub tags things based on git tags.

**Comment by e-karge** [comment]
Okay, I will do that. But I have not enough time at hand to support older versions, i.e. bugfixes and features will only go to the current version.

**Comment by e-karge** [comment]
Tags for `1.2.0`, `1.3.0` and `1.3.1` created.

**Comment by smazurov** [comment]
Thanks!
